engines:
  duplication:
    enabled: false
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    config:
      config: ./.eslintrc.yml
  fixme:
    enabled: false
ratings:
  paths:
  - "**.js"
exclude_paths:
  - test/